GET https://futdb-cms-api-production.up.railway.app/items/user_metadata/1

###


GET https://futdb-cms-api-production.up.railway.app/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1MTExNmVhLTMzYmYtNGIzNC1hNWM3LTQ5MTBhYzBmYzE4MCIsInJvbGUiOiI0Nzk3YjJkMC0xNTYwLTQxNDEtYTM1Yy1jZDY2NGZjOTVlMTciLCJhcHBfYWNjZXNzIjp0cnVlLCJhZG1pbl9hY2Nlc3MiOmZhbHNlLCJpYXQiOjE3MTA0NDc0MTEsImV4cCI6MTcxMDQ0ODMxMSwiaXNzIjoiZGlyZWN0dXMifQ.CPilXXcQmi1ndZ0rO-ZFNjcbuam1jv9Sl8zlm32dcfE

###
GET https://futdb-cms-api-production.up.railway.app/items/user_metadata/1?fields[]=id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1MTExNmVhLTMzYmYtNGIzNC1hNWM3LTQ5MTBhYzBmYzE4MCIsInJvbGUiOiI0Nzk3YjJkMC0xNTYwLTQxNDEtYTM1Yy1jZDY2NGZjOTVlMTciLCJhcHBfYWNjZXNzIjp0cnVlLCJhZG1pbl9hY2Nlc3MiOmZhbHNlLCJpYXQiOjE3MTA0NDc1MjksImV4cCI6MTcxMDQ0ODQyOSwiaXNzIjoiZGlyZWN0dXMifQ.B3j5TQGqvfUp063io-XFOUcfxDzyHX75IqLUHIoxypw